fix#11 - backend for student landing page
PS-Division-BITS/TMS pull request #16
Opened 2020-02-08 16:55 UTC by devansh-299

Fixes #11 

Changes Done :-
* Added urls/views needed
* Added html files for testing
* Requires login so tested using changes done in #14 but those changes are not included in this PR

2020-02-08 19:21 UTC, devansh-299 commented
@ChetanKhanna since the master has been updated, should I update the PR with merge conflicts resolved?

2020-02-08 19:34 UTC, ChetanKhanna commented
Yes please do.

2020-02-09 09:56 UTC, ChetanKhanna requested changes
Thanks for this! I left a comment.

2020-02-09 09:56 UTC, ChetanKhanna commented on transfers/views/dashboard_views.py
> +        'pending_applications': pending_applications})
Turn it into a CBV please.

2020-02-10 16:45 UTC, ChetanKhanna approved these changes

2020-02-10 16:47 UTC, merged