fixes#31 - populating script added
PS-Division-BITS/TMS pull request #39
Opened 2020-02-12 05:37 UTC by devansh-299

## How to use

* Make TMS as present working directory
* `pip install faker`
* `pip install factory_boy`
* `python populate_data.py`

2020-02-12 15:16 UTC, ChetanKhanna commented
@nrupeshsurya

2020-02-13 07:09 UTC, nrupeshsurya commented
@ChetanKhanna

2020-02-14 19:40 UTC, ChetanKhanna requested changes
I'll suggest you some changes, tough to write here.

2020-02-14 20:35 UTC, ChetanKhanna approved these changes

2020-02-14 20:35 UTC, merged